### PR TITLE
Enable sixpair on Windows.

### PR DESCRIPTION
**Pull request by egorpugin**
Hi,

This PR enables sixpair build on Windows.
It
1) downloads dependencies (dirent, libusb, libusbcompat),
2) builds them and
3) links them to psmove target.

The problem is that current code works with libusb driver (from older windows versions or something like that). Libusb can be installed on windows using https://zadig.akeo.ie/
But with it, move controller cannot be used with bluetooth.

Default windows 10 driver is HIDUSB. With it sixpair.c code does not work and I'm not sure if it possible to make it work.

See following links describing the problem:
https://wiibrew.org/wiki/Sixaxis
> However, the SIXAXIS will not transmit any data until a special HID feature report is read, but Windows HID functions do not allow that feature report to be read due to the incorrect HID descriptor.

Also see https://twitter.com/NefariusMaximus/status/770517683875876864

@thp 
What do you think about it? Is it possible to make sixpair work via HIDUSB driver?
Anyways, please review the PR.

### CODE REVIEW

**Comment by egorpugin** [comment]
I think that's because `image: Visual Studio 2017`.
Do you consider moving to VS2019?

**Comment by thp** [comment]
Yes, you can change it in the AppVeyor config in the pull request to see if
that helps.

Egor Pugin <notifications@github.com> schrieb am Di., 28. Juli 2020, 11:29:

**Comment by egorpugin** [comment]
@thp 
Can you take a look? Mingw issue is gone, but there are some java errors on travis CI and appveyor errors. (I did not touch that stuff. Seems like master branch changes affect that.)

**Comment by thp** [comment]
@egorpugin For the java-related error, just rebase on top of `master` (or merge `master` into your branch), @nitsch has fixed it in master.

**Comment by thp** [comment]
And the other build issue is probably worked around by #413 (just pushed, waiting to build).

**Comment by thp** [comment]
Try rebasing on master, then it should build in CI and we can have another look :)

**Comment by egorpugin** [comment]
Looks good now.

**Review by thp — APPROVED** [review]
Cool, thanks for implementing this!

**Pull request merged**
