### PR TITLE
Add free resource pseye for Test Tracker cam calibrat

### PR DESCRIPTION
**Pull request by Zangetsu38**
Fix release resource camera if you press esc for exit.

PS: works only with press Esc, and no with close console debug

### CODE REVIEW

**Comment by Zangetsu38** [comment]
Yes, but i have not found how set this :/

**Comment by nitsch** [comment]
Not exactly sure what the problem is. Merged the simplified version as c3d42010a3564e9b9fb54d820b8cf9128ec54a5b.

Thanks.

**Comment by nitsch** [comment]
I have trouble understanding you. Are you saying that you cannot close 
the window (by pressing the Escape key)?

If you are having problems with this example program, please open a 
ticket and describe them in more detail.

**Comment by Zangetsu38** [comment]
Oups, no i want said, is good, this code pushed works same my code

**Pull request closed without merging**
