### PR TITLE
Fixes to Java and Csharp bindings (Fixes #383 and possibly #341)

### LINKED ISSUE #383: Mingw cross compile not generating java bindings
When I cross compile using mingw64 the java binding files are not generated. I'm using a codenvy instance to build using the buildscript provided. 

I had to revert bindings/CMakeLists.txt to a previous version because swig_add_library() was causing an error that was not letting build anything. After the change back to swig_add_module() it built ok. 

Attached are the CMake{Output,Error}.log 
[CMakeError.log](https://github.com/thp/psmoveapi/files/3188731/CMakeError.log)
[CMakeOutput.log](https://github.com/thp/psmoveapi/files/3188732/CMakeOutput.log)

I woldn't mind to have the files provided together with the release packages, just as it happens with the python bindings.

### PR DESCRIPTION
**Pull request by rafaellago**
Added fixes to the mingw compilation of java bindings, and changed the build to package csharp and java if they happen to exist in the build dir.

Also changed the install_dependencies.sh to use default-jdk since java8 since the current java version is already 11.

### CODE REVIEW

**Comment by rafaellago** [comment]
Oh. At least it was a simple mistake, I'll have this fixed after work.

**Comment by rafaellago** [comment]
MSVC tests has passed. But I still would advise for some review of what I done since I went to a lot of unknown territory on this.

**Comment by rafaellago** [comment]
I was doing some tests and for some reason the windows build could not load everything if the libpsmoveapi.dll and libpsmoveapi_tracker.dll weren't loaded through System.loadLibrary, so I added a check for OS and if windows it'll load the other required dlls also. While I was at it, I made a change to compile the java codes to comply with version 8 so it increases compatibility.

**Comment by thp** [comment]
Perfect, thanks for the update!

**Pull request merged**
