### PR TITLE
Make Bluetooth pairing/connecting work in Windows 8

### PR DESCRIPTION
**Pull request by nitsch**
This adds setting the device's "VirtuallyCabled" property in the registry to the psmovepair utility. @betonme @cboulay  and other Windows 8 users: please test!

### CODE REVIEW

**Comment by nitsch** [comment]
@PolGraphic Could you please test this, too?

**Comment by betonme** [comment]
It builds, but actually it's not working for me.

I've tried to inculde the BT Inquiry and the remove device handling, without luck.

**Comment by nitsch** [comment]
> It builds, but actually it's not working for me.

Have you tried building with -DPSMOVE_USE_DEBUG=1 for debug output? That
would help determine why/where it fails.

**Comment by betonme** [comment]
Yes, that was my second attemp.

There was no specific error.
Just the verify is not successful.

**Comment by nitsch** [comment]
> Yes, that was my second attemp.
> 
> There was no specific error.
> Just the verify is not successful.

So there is absolutely no "Failed to ..." in the debug output?

Does manually setting the device's VirtuallyCabled property in the
registry still make it work?

**Comment by betonme** [comment]
Correct. Theres is no failed in the output.
I've tried it several times.

And yes setting the VirtuallyCabled manually or using the psmovepair-win utility is working.

**Comment by cboulay** [comment]
I finally got a chance to try today. Unfortunately, it didn't work for me either.

I couldn't build it with my mingw-w64 (x86_64). I'm downloading an i686 version now.

I applied the pull request as a patch to my master branch then was able to build with MSVC2013. I configured the build with -DPSMOVE_USE_DEBUG=1, opened a command prompt as administrator, then ran psmovepair. The output is below. There were no failure messages in the output.

Immediately after this I attempted to run the modified psmove-pair-win and it was not behaving correctly. The time between messages seemed longer, and sometimes it reported "device disconnected" which never happened before.

I checked-out my master branch again, built psmovepair, ran that, then ran psmove-pair-win again and everything worked as it did previously.

```
Connected controllers: 1
[PSMOVE DEBUG] Current host: 5c:f3:70:64:54:10
[PSMOVE DEBUG] Current host: 5c:f3:70:64:54:10
PSMove #1 connected via USB.
[PSMOVE DEBUG] Current host: 5c:f3:70:64:54:10
[PSMOVE DEBUG] Already paired.
[PSMOVE DEBUG] Making radio discoverable

    Unplug the controller.

    Now press the controller's PS button. The red status LED
    will start blinking. Whenever it goes off, press the
    PS button again. Repeat this until the status LED finally
    remains lit. Press Ctrl+C to cancel anytime.
[PSMOVE DEBUG] Found Move Motion Controller matching the given address
[snip repeated 25 times]
[PSMOVE DEBUG] Checking HID service ...
[PSMOVE DEBUG] Patching the registry ...
[PSMOVE DEBUG] Verifying successful connection ...
[PSMOVE DEBUG] Found Move Motion Controller matching the given address
```

**Comment by nitsch** [comment]
@cboulay @brendanwalker Like I said this was just me pausing work on that port a few weeks ago. Not exactly sure if that should already work on Windows 8, but please test and let me know. ;)

**Comment by nitsch** [comment]
@thp @cboulay Phew, I have finally gotten the new Windows pairing into a working shape and successfully tested it on Windows XP, 7, 8.1, and 10. I'd say this is ready for merging. Yay, no need anymore for my [psmove-pair-win](https://github.com/nitsch/psmove-pair-win) as separate pairing tool on Windows 8 and later.

**Comment by brendanwalker** [comment]
@nitsch Thanks for looking testing this on those older platforms! I'll pull this down into psmove-unity5 and talk to @cboulay about pulling this in psmove-ue4.

**Comment by thp** [comment]
Cool stuff; want to have that for the next release :)

**Pull request merged**
