### PR TITLE
psmoveapi for Windows 8.1 x64

### PR DESCRIPTION
**Pull request by betonme**
I've started working on a port for Windows 8.

Now it could be compiled.
The calibration is working.
Added basic support for the navigation controller.

Tested with Win8.1 x64
mingw32-i686-4.8.3-release-win32-sjlj-rt_v3-rev0
cmake-2.8.12.2-win32-x86

### CODE REVIEW

**Comment by thp** [comment]
How does this relate to https://github.com/thp/psmoveapi/pull/149 ? Should we aim to get both pull requests merged into a single pull request? This pull request looks cleaner, the other has indentation issues, but both try to solve the same problem? // cc @cboulay

**Comment by cboulay** [comment]
@thp They do both try to solve the same problem and #149 uses the basic same technique that this one did. However, this one never worked for me. There is a small difference that I can't recall right now and I don't have time to reinvestigate because I have to take my daughter to swimming. By the time I get back to working on this, Europe will be asleep.

**Comment by thp** [comment]
So this is superseded by #149 then, and #149 should be reviewed/merged instead of this one?

**Comment by cboulay** [comment]
Yes, I believe so. But, as @betonme mentioned in #149, the changes in #149 (and I suspect this PR, too) expose another problem. I have a question for you about that, but I'll ask it in #149.

**Comment by Lirrec** [comment]
As #149 is already merged, shouldn't this one be closed?

**Comment by thp** [comment]
Closing this now. Please rebase/reopen if it's still relevant.

**Pull request closed without merging**
