### PR TITLE
Support for MSVC 2013

### PR DESCRIPTION
**Pull request by cboulay**
First 2 commits are the same as in #180.
This supercedes #163

### CODE REVIEW

**Comment by cboulay** [comment]
I'm in the process of updating this to have a smaller footprint similar to @polyarcgames changes [here](https://github.com/PolyarcGames/psmoveapi/commit/1e21985670d80d073696601b8d1f5e14202b2212).

**Comment by thp** [comment]
Any updates here?

**Comment by cboulay** [comment]
I haven't looked at this in a while and I don't really have the time to do it now.

It's become a bit of a nightmare because there have been some changes to your repo since I started the process and there were some non-MSVC-specific changes that crept into my working branch. Some of which conflicted with what you had. I attempted to `rebase -i` and ended up with the same commits being done over and over. You can see that [here](https://github.com/thp/psmoveapi/compare/master...cboulay:simpler_msvc).

I don't blame you for not wanting to pull that. Making a new branch that has ONLY the msvc-related changes will take me several hours and I don't have that kind of time these days. Someone else is welcome to reproduce only the necessary changes based off my work linked above.

**Comment by thp** [comment]
Closing in favor of #190.

**Pull request closed without merging**
