### PR TITLE
Dead Reckoning (Work in Progress)

### PR DESCRIPTION
**Pull request by ccoenen**
Discussion, Details in #160

### CODE REVIEW

**Comment by thp** [comment]
See https://github.com/thp/psmoveapi/issues/160 for discussion items. Please continue the discussion here.

**Comment by thp** [comment]
Any news on this one?

**Comment by ccoenen** [comment]
Not from my part, sorry. I've since moved on to other projects and sadly don't even own a PSMove-Controller.

**Comment by thp** [comment]
No problem, thanks for the reply - closing.

**Pull request closed without merging**
