### PR TITLE
Update Windows script where possible

### PR DESCRIPTION
**Pull request by kcoul**
The libusb patches still need to be updated, external cloning has been updated in https://github.com/thp/psmoveapi/commit/8caf07acd9d03affc066e314f762df08f070cfb8

### CODE REVIEW

**Comment by thp** [comment]
The submodule update is now in 8caf07acd9d03affc066e314f762df08f070cfb8, you probably have to rebase against the new master revision.

**Comment by kcoul** [comment]
> The submodule update is now in [8caf07a](https://github.com/thp/psmoveapi/commit/8caf07acd9d03affc066e314f762df08f070cfb8), you probably have to rebase against the new master revision.

Rebased, thanks.

**Comment by kcoul** [comment]
It looks like AppVeyor is having a problem expecting CMakeLists.txt in external folder. I didn't encounter this issue in my local build.

**Comment by thp** [comment]
> It looks like AppVeyor is having a problem expecting CMakeLists.txt in external folder. I didn't encounter this issue in my local build.

Nah, it's yet another `git://` URL issue that I forgot to fix up.

See https://github.com/thp/psmoveapi/commit/87147ffa0ac8e01883ba2a9e05ff7be615d3dab8 and this is now in master, so maybe if you rebase one more time, it will work - fingers crossed :)

**Comment by kcoul** [comment]
> > It looks like AppVeyor is having a problem expecting CMakeLists.txt in external folder. I didn't encounter this issue in my local build.
> 
> Nah, it's yet another `git://` URL issue that I forgot to fix up.
> 
> See [87147ff](https://github.com/thp/psmoveapi/commit/87147ffa0ac8e01883ba2a9e05ff7be615d3dab8) and this is now in master, so maybe if you rebase one more time, it will work - fingers crossed :)

Looks good now!

**Comment by thp** [comment]
Merged, thanks. What was that about the libusb patches?

**Comment by kcoul** [comment]
> Merged, thanks. What was that about the libusb patches?

L.42 of build_msvc.bat attempts to apply a specific patch to generate dynamic rather than static libraries for libusb, but for me the patch could not apply. The base file has probably changed. It seems in fact that libusb now contains DLL versions of the vcxproj files, so perhaps patching is no longer necessary? https://github.com/libusb/libusb/tree/master/msvc

**Comment by thp** [comment]
Yeah, let's see. The AppVeyor build seems to still properly apply the patch from what I can tell from the logs:

https://ci.appveyor.com/project/thp/psmoveapi/builds/43178619/job/7qpqt34l2sld2vbe?fullLog=true

```
[...]
[00:00:32] + ./scripts/visualc/build_msvc.bat 2017 x64
[00:00:32] The system cannot find the path specified.
[00:00:32] Applying libusb dynamic CRT patch...
[00:00:32] 
[00:00:32] Building libusb (Debug)
[00:00:33] Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
[00:00:33] Copyright (C) Microsoft Corporation. All rights reserved.
[00:00:33] 
[00:00:37]   core.c
[...]
```

**Comment by kcoul** [comment]
> Yeah, let's see. The AppVeyor build seems to still properly apply the patch from what I can tell from the logs:
> 
> https://ci.appveyor.com/project/thp/psmoveapi/builds/43178619/job/7qpqt34l2sld2vbe?fullLog=true
> 
> ```
> [...]
> [00:00:32] + ./scripts/visualc/build_msvc.bat 2017 x64
> [00:00:32] The system cannot find the path specified.
> [00:00:32] Applying libusb dynamic CRT patch...
> [00:00:32] 
> [00:00:32] Building libusb (Debug)
> [00:00:33] Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
> [00:00:33] Copyright (C) Microsoft Corporation. All rights reserved.
> [00:00:33] 
> [00:00:37]   core.c
> [...]
> ```

I think this must be due to cloning a very specific hash of libusb1.0, IIRC? I believe I have verified that the latest release of libusb1.0 also works correctly, so there is the choice to update it, to more easily support newer MSCVC and avoid the need to patch (since static vcxproj files are now provided).

**Pull request merged**
