### PR TITLE
updated to opencv 3

### PR DESCRIPTION
**Pull request by adangert**
fixes issues in https://github.com/thp/psmoveapi/issues/387

### CODE REVIEW

**Comment by thp** [comment]
It looks like the build scripts also need to be updated to use OpenCV 3.

**Comment by thp** [comment]
Thanks, moving this to #391 since some other fixes also need to be put on top of this.

**Comment by nitsch** [comment]
@adangert @rpavlik Did you try running the test_tracker example on Windows after this upgrade to OpenCV 3? Did it still work?

**Comment by adangert** [comment]
I haven't tried rebuilding the psmoveapi on windows since I had it working previously.

**Pull request closed without merging**
